# 训练配置
train:
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  early_stopping_patience: 10

  optimizer_name: 'adamw'
  
  loss_name: 'cross_entropy'

  scheduler_name: 'cosineannealing'

  device: 'cuda'

# 数据配置
data:
  dataset_path: "CV_Torch/II.IP102_Classification/data/raw/img_class.txt"
  size: 256
  batch_size: 256
  num_workers: 0
  train_split: 0.8
  split_seed: 42
  transform: True
  pin_memory: True  

# 模型配置
model:
  name: "resnet34"
  num_classes: 102
  pretrained: false
  
# 实验配置
exp:
  name: "exp_001"
  save_dir: "./experiments/exp_001"
  # 每10个batch记录一次
  log_interval: 10